@startuml "Use Case Diagram"
actor User
package "Python MRO Extension" {
    rectangle "CodeLens" {
        usecase CLS as \
        "CodeLens Show
        ==
        Show class MRO list in
        the CodeLens section."
        usecase CLJ as \
        "CodeLens Jump
        ==
        Jump to class definition
        by clicking class name
        in the MRO list."
    }
    rectangle "Hover" {
        usecase HC as \
        "Hover Class
        ==
        Append the class MRO list
        in the popped window when
        hovering over a class."
        usecase HO as \
        "Hover Object
        ==
        Append the class MRO list
        in the popped window when
        hovering over an object and
        if its type can be parsed."
    }
    rectangle "Hover Method" {
        usecase HCM as \
        "Hover Class Method
        ==
        Append the actual class
        fulfilling the method call
        in the popped window when
        hovering over a
        class method."
        usecase HOM as \
        "Hover Object Method
        ==
        Append the actual class
        fulfilling the method call
        in the popped window
        when hovering over an
        object method and if its
        type can be parsed."
    }
}
left to right direction
User --> CLS
User --> CLJ
User --> HC
User --> HO
User --> HCM
User --> HOM
@enduml