name: Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python-version: [3.7, 3.8]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - run: npm install
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{matrix.python-version}}
    - name: Install pipenv and python packages
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install
    - name: Run tests
      uses: GabrielBB/xvfb-action@v1.2
      with:
        run: npm test
